# Generated by Django 5.0 on 2024-03-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('middleName', models.CharField(blank=True, max_length=20, null=True)),
                ('lastName', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=20)),
                ('Pin', models.IntegerField()),
                ('beginingBalance', models.IntegerField()),
            ],
        ),
    ]
