# Generated by Django 5.0 on 2024-04-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0003_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currentBalance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
