# Generated by Django 5.0 on 2024-04-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0004_account_currentbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='currentBalance',
        ),
    ]
