# Generated by Django 5.0 on 2024-04-04 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0006_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
